application:
  runtimeManifest:
    packages:
      demoslack:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
              API_ENDPOINT: $API_ENDPOINT
            annotations:
              require-adobe-auth: false
              final: true
            relations:
              event-listener-for: []
          slack-event:
            function: actions/slack-event/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true

